version: '3'

services:
  db:
    build: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/code/db

  fastapi:
    build: fastapi
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./fastapi:/code/fastapi
    ports:
      - "80:80"
