version: '3'

services:
  db:
    build: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/code/db

  fastapi:
    build: fastapi_app
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./fastapi_app:/code/fastapi_app
    ports:
      - "80:80"
